import test from 'node:test';
import assert from 'node:assert/strict';
import { runSmoke } from '../scripts/live-smoke.mjs';

const health = { status: 200, body: { ok: true, plugin: { id: 'st-bainiaodata', version: '0.1.0' }, api: { current: 1, supported: [1] }, storage: { path: 'hidden' }, capabilities: { records: true, recordList: true, optimisticRevision: true, atomicReplace: true, trash: true, trashRestore: true, pagination: false, batchTransactions: false, trashGc: false, auditLog: false, diagnosticExport: false } } };
test('full smoke seam walks CRUD, 409, trash and restore without logging payloads', async () => {
  const calls = []; const secret = 'cookie-secret-csrf-secret'; const responses = [health, { status: 200, body: { revision: 1, generationId: 'generation-1', data: { smoke: true, recordId: 'record-fixed', phase: 'created' } } }, { status: 200, body: { revision: 1, generationId: 'generation-1', data: { smoke: true, recordId: 'record-fixed', phase: 'created' } } }, { status: 200, body: { revision: 2, generationId: 'generation-1', data: { smoke: true, recordId: 'record-fixed', phase: 'updated', marker: 'live-smoke' } } }, { status: 409, body: { error: 'conflict', currentRevision: 2 } }, { status: 200, body: { trashId: 'generation-1-2', deletedRevision: 2 } }, { status: 200, body: [{ trashId: 'generation-1-2', namespace: 'smoke-fixed', collection: 'records', recordId: 'record-fixed', generationId: 'generation-1', revision: 2 }] }, { status: 200, body: { revision: 2, generationId: 'generation-1', data: { smoke: true, recordId: 'record-fixed', phase: 'updated', marker: 'live-smoke' } } }, { status: 200, body: { revision: 2, data: { smoke: true, recordId: 'record-fixed', phase: 'updated', marker: 'live-smoke' } } }];
  const logs = []; const result = await runSmoke({ randomId: () => 'fixed', log: (line) => logs.push(line), request: async (path, options) => { calls.push({ path, options }); return responses.shift(); } }); assert.equal(result.revision, 2); assert.equal(calls.length, 9); assert.match(calls[1].path, /smoke-fixed/u); assert.equal(calls[4].options.body.includes('expectedRevision":1'), true); assert.equal(logs.length, 1); assert.equal(logs[0].includes(secret), false); assert.equal(logs[0].includes('live-smoke'), false);
});
test('smoke rejects malformed critical health and create responses', async () => { const badHealth = { ...health, body: { ...health.body, api: { current: 2, supported: [2] } } }; await assert.rejects(runSmoke({ request: async () => badHealth, randomId: () => 'x', log: () => {} }), /health API/u); const validHealthThenBadCreate = async (path) => path === '/v1/health' ? health : { status: 200, body: { revision: 1, generationId: '', data: {} } }; await assert.rejects(runSmoke({ request: validHealthThenBadCreate, randomId: () => 'x', log: () => {} }), /创建/u); });
