import test from 'node:test';
import assert from 'node:assert/strict';
import { fetchJsonWithTimeout, main, runSmoke, createApiRequest, createSession, capabilities } from '../scripts/live-smoke.mjs';

const envelope = (revision, generationId, data) => ({ schemaVersion: 1, revision, generationId, createdAt: '2026-01-01T00:00:00.000Z', updatedAt: revision === 1 ? '2026-01-01T00:00:00.000Z' : '2026-01-01T00:00:01.000Z', data });
const health = { status: 200, body: { ok: true, plugin: { id: 'st-bainiaodata', name: 'Bainiao Data', version: '0.1.0' }, api: { current: 1, supported: [1] }, storage: { scope: 'user-root', path: 'hidden', envelopeSchemaVersion: 1 }, capabilities } };
test('严格校验完整请求路径、方法、body及完整 envelope', async () => {
  const calls = []; const generationId = 'generation-1'; const created = envelope(1, generationId, { smoke: true, recordId: 'record-fixed', phase: 'created' }); const updated = envelope(2, generationId, { smoke: true, recordId: 'record-fixed', phase: 'updated', marker: 'live-smoke' }); const deletedAt = '2026-01-01T00:00:02.000Z'; const trashId = `${generationId}-2`;
  const responses = [health, { status: 200, body: created }, { status: 200, body: created }, { status: 200, body: updated }, { status: 409, body: { error: 'conflict', message: 'Revision conflict', currentRevision: 2 } }, { status: 200, body: { trashId, deletedAt, deletedRevision: 2 } }, { status: 200, body: [{ trashId, namespace: 'smoke-fixed', collection: 'records', recordId: 'record-fixed', generationId, revision: 2, originalPath: 'smoke-fixed/records/record-fixed.json', deletedAt, deletedRevision: 2, expiresAt: '2026-02-01T00:00:02.000Z' }] }, { status: 200, body: updated }, { status: 200, body: updated }];
  const result = await runSmoke({ randomId: () => 'fixed', log: () => {}, request: async (path, options = {}) => { calls.push({ path, options }); return responses.shift(); } }); assert.equal(result.revision, 2);
  assert.deepEqual(calls.map((call) => [call.options.method ?? 'GET', call.path]), [['GET', '/v1/health'], ['PUT', '/v1/records/smoke-fixed/records/record-fixed'], ['GET', '/v1/records/smoke-fixed/records/record-fixed'], ['PUT', '/v1/records/smoke-fixed/records/record-fixed'], ['PUT', '/v1/records/smoke-fixed/records/record-fixed'], ['DELETE', '/v1/records/smoke-fixed/records/record-fixed'], ['GET', '/v1/trash/smoke-fixed'], ['POST', '/v1/trash/smoke-fixed/generation-1-2/restore'], ['GET', '/v1/records/smoke-fixed/records/record-fixed']]); assert.deepEqual(JSON.parse(calls[1].options.body), { data: { smoke: true, recordId: 'record-fixed', phase: 'created' }, expectedRevision: 0 }); assert.deepEqual(JSON.parse(calls[5].options.body), { expectedRevision: 2 });
});
test('错误合同、409 变 200 和关键字段缺失都会失败', async () => { await assert.rejects(runSmoke({ request: async () => ({ ...health, body: { ...health.body, api: { current: 2, supported: [2] } } }), randomId: () => 'x', log: () => {} }), /health API/u); await assert.rejects(runSmoke({ request: async (path) => path === '/v1/health' ? health : { status: 200, body: envelope(1, 'g', {}) }, randomId: () => 'x', log: () => {} }), /创建/u); });
test('会话支持多 Set-Cookie、注入传输并保留完整 URL', async () => { const seen = []; const fetchImpl = async (url, options) => { seen.push({ url, options }); return { status: 200, headers: { getSetCookie: () => ['a=1; Path=/', 'b=2; HttpOnly'] }, json: async () => ({ token: 'csrf' }) }; }; const session = await createSession({ baseUrl: 'http://example.test', fetchImpl }); assert.deepEqual(session, { cookie: 'a=1; b=2', token: 'csrf' }); const request = createApiRequest({ baseUrl: 'http://example.test', ...session, fetchImpl }); await request('/v1/records/a%2Fb/x/y'); assert.equal(seen[1].url, 'http://example.test/api/plugins/st-bainiaodata/v1/records/a%2Fb/x/y'); assert.equal(seen[1].options.headers.Cookie, 'a=1; b=2'); });
test('缺 CSRF token 或 cookie 会安全失败', async () => { const noToken = async () => ({ status: 200, headers: { getSetCookie: () => ['a=1'] }, json: async () => ({}) }); const noCookie = async () => ({ status: 200, headers: { getSetCookie: () => [] }, json: async () => ({ token: 'csrf' }) }); await assert.rejects(createSession({ baseUrl: 'http://x', fetchImpl: noToken }), /登录会话获取失败/u); await assert.rejects(createSession({ baseUrl: 'http://x', fetchImpl: noCookie }), /登录会话获取失败/u); });
test('超时覆盖响应头和 body，CLI 缺 URL 为 2、其他失败为 1，日志不泄露', async () => { const headerTimeout = async (_url, options) => new Promise((_, reject) => options.signal.addEventListener('abort', () => reject(Object.assign(new Error('secret'), { name: 'AbortError' })))); await assert.rejects(fetchJsonWithTimeout('http://header-timeout', {}, 1, headerTimeout), /请求超时/u); const bodyTimeout = async (_url, options) => ({ status: 200, headers: {}, json: () => new Promise((_, reject) => options.signal.addEventListener('abort', () => reject(Object.assign(new Error('secret'), { name: 'AbortError' })))) }); await assert.rejects(fetchJsonWithTimeout('http://body-timeout', {}, 1, bodyTimeout), /请求超时/u); const logs = []; assert.equal(await main({ argv: ['node', 'script'], errorLog: (line) => logs.push(line) }), 2); assert.equal(await main({ argv: ['node', 'script', 'http://x'], fetchImpl: async () => { throw new Error('secret'); }, errorLog: (line) => logs.push(line) }), 1); assert.equal(logs.join('\n').includes('secret'), false); });
