import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm, readFile, mkdir, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { info, init } from '../index.mjs';

const router = () => { const routes = []; const add = (method) => (path, handler) => routes.push({ method, path, handler }); return { routes, get: add('get'), put: add('put'), delete: add('delete'), post: add('post') }; };
test('formal identity, V1 routes, health contract and no path leak', async () => {
  assert.deepEqual({ id: info.id, name: info.name, version: info.version }, { id: 'st-bainiaodata', name: 'Bainiao Data', version: '0.1.0' });
  const r = router(); init(r); assert.deepEqual(r.routes.map(({ method, path }) => [method, path]), [['get','/v1/health'],['get','/v1/records/:namespace/:collection/:recordId'],['put','/v1/records/:namespace/:collection/:recordId'],['get','/v1/records/:namespace/:collection'],['delete','/v1/records/:namespace/:collection/:recordId'],['get','/v1/trash/:namespace'],['post','/v1/trash/:namespace/:trashId/restore']]);
  const root = await mkdtemp(join(tmpdir(), 'bainiao-contract-')); try { const route = r.routes[0].handler; const response = { statusCode: 0, body: null, status(code) { this.statusCode = code; return this; }, json(body) { this.body = body; } }; await route({ user: { directories: { root } } }, response); assert.equal(response.statusCode, 200); assert.deepEqual(response.body.plugin, { id: info.id, name: info.name, version: info.version }); assert.deepEqual(response.body.api, { current: 1, supported: [1] }); assert.deepEqual(response.body.capabilities, { records: true, recordList: true, optimisticRevision: true, atomicReplace: true, trash: true, trashRestore: true, pagination: false, batchTransactions: false, trashGc: false, auditLog: false, diagnosticExport: false }); assert.equal(response.body.storage.path, 'hidden'); assert.equal(JSON.stringify(response.body).includes(root), false); } finally { await rm(root, { recursive: true, force: true }); }
});
test('package version follows runtime identity', async () => { const packageData = JSON.parse(await readFile(new URL('../package.json', import.meta.url), 'utf8')); assert.equal(packageData.name, info.id); assert.equal(packageData.version, info.version); });
test('route error statuses are stable and sanitized', async () => { const r = router(); init(r); const root = await mkdtemp(join(tmpdir(), 'bainiao-errors-')); const response = () => ({ statusCode: 0, body: null, status(code) { this.statusCode = code; return this; }, json(body) { this.body = body; } }); const req = (params, body = {}) => ({ user: { directories: { root } }, params, body }); const get = r.routes.find((x) => x.method === 'get' && x.path.includes(':recordId')).handler; const put = r.routes.find((x) => x.method === 'put').handler; try { const missing = response(); await get(req({ namespace: 'n', collection: 'c', recordId: 'missing' }), missing); assert.equal(missing.statusCode, 404); const bad = response(); await put(req({ namespace: 'n', collection: 'c', recordId: 'r' }, { data: {}, expectedRevision: 0 }), bad); assert.equal(bad.statusCode, 200); const conflict = response(); await put(req({ namespace: 'n', collection: 'c', recordId: 'r' }, { data: {}, expectedRevision: 0 }), conflict); assert.equal(conflict.statusCode, 409); const malformed = join(root, '.st-bainiaodata', 'storage-v1', 'records', 'n', 'c', 'broken.json'); await mkdir(join(root, '.st-bainiaodata', 'storage-v1', 'records', 'n', 'c'), { recursive: true }); await writeFile(malformed, '{'); const server = response(); await get(req({ namespace: 'n', collection: 'c', recordId: 'broken' }), server); assert.equal(server.statusCode, 500); for (const result of [missing, conflict, server]) assert.equal(JSON.stringify(result.body).includes(root), false); } finally { await rm(root, { recursive: true, force: true }); } });
test('400 validation response is sanitized', async () => { const r = router(); init(r); const root = await mkdtemp(join(tmpdir(), 'bainiao-400-')); const response = { statusCode: 0, body: null, status(code) { this.statusCode = code; return this; }, json(body) { this.body = body; } }; try { await r.routes.find((x) => x.method === 'put').handler({ user: { directories: { root } }, params: { namespace: 'n', collection: 'c', recordId: 'r' }, body: { data: {} } }, response); assert.equal(response.statusCode, 400); assert.equal(response.body.error, 'validation'); assert.equal(JSON.stringify(response.body).includes(root), false); } finally { await rm(root, { recursive: true, force: true }); } });
