import { randomUUID } from 'node:crypto';
import { pathToFileURL } from 'node:url';

export const capabilities = { records: true, recordList: true, optimisticRevision: true, atomicReplace: true, trash: true, trashRestore: true, pagination: false, batchTransactions: false, trashGc: false, auditLog: false, diagnosticExport: false };
const assertValue = (condition, message) => { if (!condition) throw new Error(message); };
const equalJson = (left, right) => JSON.stringify(left) === JSON.stringify(right);
export async function runSmoke({ request, randomId = randomUUID, log = console.log }) {
  const namespace = `smoke-${randomId()}`; const recordId = `record-${randomId()}`; const health = await request('/v1/health');
  assertValue(health.status === 200 && health.body.ok === true, 'health 响应不符合预期'); assertValue(health.body.plugin?.id === 'st-bainiaodata' && health.body.plugin?.version === '0.1.0', 'health 插件合同不符合预期'); assertValue(health.body.api?.current === 1 && equalJson(health.body.api?.supported, [1]), 'health API 合同不符合预期'); assertValue(equalJson(health.body.capabilities, capabilities) && health.body.storage?.path === 'hidden', 'health 能力或路径合同不符合预期');
  const path = `/records/${encodeURIComponent(namespace)}/records/${encodeURIComponent(recordId)}`; const createdData = { smoke: true, recordId, phase: 'created' }; const created = await request(path, { method: 'PUT', body: JSON.stringify({ data: createdData, expectedRevision: 0 }) }); assertValue(created.status === 200 && created.body.revision === 1 && typeof created.body.generationId === 'string' && equalJson(created.body.data, createdData), '创建响应不符合预期');
  const firstRead = await request(path); assertValue(firstRead.status === 200 && equalJson(firstRead.body.data, createdData), '读取响应不符合预期'); const updatedData = { smoke: true, recordId, phase: 'updated', marker: 'live-smoke' }; const updated = await request(path, { method: 'PUT', body: JSON.stringify({ data: updatedData, expectedRevision: 1 }) }); assertValue(updated.status === 200 && updated.body.revision === 2 && updated.body.generationId === created.body.generationId && equalJson(updated.body.data, updatedData), '更新响应不符合预期');
  const stale = await request(path, { method: 'PUT', body: JSON.stringify({ data: { stale: true }, expectedRevision: 1 }) }); assertValue(stale.status === 409 && stale.body.error === 'conflict' && stale.body.currentRevision === 2, '旧 revision 未返回预期冲突'); const deleted = await request(path, { method: 'DELETE', body: JSON.stringify({ expectedRevision: 2 }) }); assertValue(deleted.status === 200 && typeof deleted.body.trashId === 'string' && deleted.body.deletedRevision === 2, '删除响应不符合预期');
  const trash = await request(`/trash/${encodeURIComponent(namespace)}`); assertValue(trash.status === 200, '回收站列表响应不符合预期'); const item = trash.body.find((entry) => entry.trashId === deleted.body.trashId); assertValue(item && item.namespace === namespace && item.collection === 'records' && item.recordId === recordId && item.generationId === created.body.generationId && item.revision === 2, '回收项不符合预期'); const restored = await request(`/trash/${encodeURIComponent(namespace)}/${encodeURIComponent(deleted.body.trashId)}/restore`, { method: 'POST', body: '{}' }); assertValue(restored.status === 200 && restored.body.revision === 2 && restored.body.generationId === created.body.generationId && equalJson(restored.body.data, updatedData), '恢复响应不符合预期'); const finalRead = await request(path); assertValue(finalRead.status === 200 && finalRead.body.revision === 2 && equalJson(finalRead.body.data, updatedData), '最终读取响应不符合预期'); log(`live smoke 成功：recordId=${recordId}，trashId=${deleted.body.trashId}，最终 revision=2。`); return { namespace, recordId, trashId: deleted.body.trashId, revision: 2 };
}
export async function fetchJsonWithTimeout(url, options = {}, timeoutMs = 10000) { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), timeoutMs); try { const response = await fetch(url, { ...options, signal: controller.signal }); const body = await response.json().catch(() => ({})); return { status: response.status, body, headers: response.headers }; } catch (error) { if (error?.name === 'AbortError') throw new Error('请求超时'); throw new Error('请求失败'); } finally { clearTimeout(timer); } }
async function main() { const baseUrl = (process.argv[2] ?? '').replace(/\/+$/u, ''); if (!baseUrl) { console.error('用法：node scripts/live-smoke.mjs <宿主基址>'); process.exitCode = 2; return; } try { const csrf = await fetchJsonWithTimeout(`${baseUrl}/csrf-token`); const cookies = typeof csrf.headers.getSetCookie === 'function' ? csrf.headers.getSetCookie() : [csrf.headers.get('set-cookie') ?? '']; const cookie = cookies.map((value) => value.split(';', 1)[0]).filter(Boolean).join('; '); const token = csrf.body.token ?? csrf.body.csrfToken; if (csrf.status < 200 || csrf.status >= 300 || !cookie || !token) throw new Error('登录会话获取失败'); const request = async (path, options = {}) => fetchJsonWithTimeout(`${baseUrl}/api/plugins/st-bainiaodata${path}`, { ...options, headers: { Accept: 'application/json', ...(options.body ? { 'Content-Type': 'application/json' } : {}), Cookie: cookie, 'X-CSRF-Token': token, ...(options.headers ?? {}) } }); await runSmoke({ request }); } catch (error) { console.error(error instanceof Error ? error.message : 'live smoke 失败'); process.exitCode = 1; } }
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) await main();
