import { randomUUID } from 'node:crypto';
import { pathToFileURL } from 'node:url';

export const capabilities = { records: true, recordList: true, optimisticRevision: true, atomicReplace: true, trash: true, trashRestore: true, pagination: false, batchTransactions: false, trashGc: false, auditLog: false, diagnosticExport: false };
const assertValue = (condition, message) => { if (!condition) throw new Error(message); };
const equalJson = (left, right) => JSON.stringify(left) === JSON.stringify(right);
const isObject = (value) => value !== null && typeof value === 'object' && !Array.isArray(value);
const assertEnvelope = (value, expected, message) => { assertValue(isObject(value), message); for (const key of ['schemaVersion', 'revision', 'generationId', 'createdAt', 'updatedAt', 'data']) assertValue(Object.hasOwn(value, key), message); assertValue(value.schemaVersion === 1 && value.revision === expected.revision && value.generationId === expected.generationId, message); assertValue(typeof value.createdAt === 'string' && typeof value.updatedAt === 'string' && equalJson(value.data, expected.data), message); };

export async function runSmoke({ request, randomId = randomUUID, log = console.log }) {
  const namespace = `smoke-${randomId()}`; const recordId = `record-${randomId()}`;
  const health = await request('/v1/health'); assertValue(health.status === 200 && health.body.ok === true, 'health 响应不符合预期'); assertValue(equalJson(health.body.plugin, { id: 'st-bainiaodata', name: 'Bainiao Data', version: '0.1.0' }), 'health 插件合同不符合预期'); assertValue(equalJson(health.body.api, { current: 1, supported: [1] }), 'health API 合同不符合预期'); assertValue(equalJson(health.body.storage, { scope: 'user-root', path: 'hidden', envelopeSchemaVersion: 1 }), 'health 存储合同不符合预期'); assertValue(equalJson(health.body.capabilities, capabilities), 'health 能力合同不符合预期');
  const path = `/v1/records/${encodeURIComponent(namespace)}/records/${encodeURIComponent(recordId)}`; const createdData = { smoke: true, recordId, phase: 'created' };
  const created = await request(path, { method: 'PUT', body: JSON.stringify({ data: createdData, expectedRevision: 0 }) }); assertValue(created.status === 200, '创建响应不符合预期'); assertEnvelope(created.body, { revision: 1, generationId: created.body?.generationId, data: createdData }, '创建响应不符合预期');
  const firstRead = await request(path); assertValue(firstRead.status === 200, '首读响应不符合预期'); assertEnvelope(firstRead.body, created.body, '首读响应不符合预期');
  const updatedData = { smoke: true, recordId, phase: 'updated', marker: 'live-smoke' }; const updated = await request(path, { method: 'PUT', body: JSON.stringify({ data: updatedData, expectedRevision: 1 }) }); assertValue(updated.status === 200, '更新响应不符合预期'); assertEnvelope(updated.body, { revision: 2, generationId: created.body.generationId, data: updatedData }, '更新响应不符合预期'); assertValue(updated.body.createdAt === created.body.createdAt, '更新时间合同不符合预期');
  const stale = await request(path, { method: 'PUT', body: JSON.stringify({ data: { stale: true }, expectedRevision: 1 }) }); assertValue(stale.status === 409 && equalJson(stale.body, { error: 'conflict', message: 'Revision conflict', currentRevision: 2 }), '旧 revision 未返回预期冲突');
  const deleted = await request(path, { method: 'DELETE', body: JSON.stringify({ expectedRevision: 2 }) }); assertValue(deleted.status === 200 && typeof deleted.body.trashId === 'string' && typeof deleted.body.deletedAt === 'string' && deleted.body.deletedRevision === 2 && Object.keys(deleted.body).length === 3, '删除响应不符合预期');
  const trash = await request(`/v1/trash/${encodeURIComponent(namespace)}`); assertValue(trash.status === 200 && Array.isArray(trash.body), '回收站列表响应不符合预期'); const item = trash.body.find((entry) => entry.trashId === deleted.body.trashId); assertValue(item && item.namespace === namespace && item.collection === 'records' && item.recordId === recordId && item.generationId === created.body.generationId && item.revision === 2 && item.originalPath === `${namespace}/records/${recordId}.json` && item.deletedAt === deleted.body.deletedAt && item.deletedRevision === 2 && typeof item.expiresAt === 'string', '回收项不符合预期');
  const restored = await request(`/v1/trash/${encodeURIComponent(namespace)}/${encodeURIComponent(deleted.body.trashId)}/restore`, { method: 'POST', body: '{}' }); assertValue(restored.status === 200, '恢复响应不符合预期'); assertEnvelope(restored.body, updated.body, '恢复响应不符合预期'); const finalRead = await request(path); assertValue(finalRead.status === 200, '最终读取响应不符合预期'); assertEnvelope(finalRead.body, updated.body, '最终读取响应不符合预期');
  log(`live smoke 成功：recordId=${recordId}，trashId=${deleted.body.trashId}，最终 revision=2。`); return { namespace, recordId, trashId: deleted.body.trashId, revision: 2 };
}

export async function fetchJsonWithTimeout(url, options = {}, timeoutMs = 10000, fetchImpl = fetch) { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), timeoutMs); try { const response = await fetchImpl(url, { ...options, signal: controller.signal }); const body = await response.json(); return { status: response.status, body, headers: response.headers }; } catch (error) { if (error?.name === 'AbortError') throw new Error('请求超时'); throw new Error('请求失败'); } finally { clearTimeout(timer); } }
const cookieHeader = (headers) => (typeof headers?.getSetCookie === 'function' ? headers.getSetCookie() : [headers?.get?.('set-cookie') ?? '']).map((value) => value.split(';', 1)[0]).filter(Boolean).join('; ');
export async function createSession({ baseUrl, fetchImpl = fetch, timeoutMs = 10000 } = {}) { const csrf = await fetchJsonWithTimeout(`${baseUrl}/csrf-token`, {}, timeoutMs, fetchImpl); const cookie = cookieHeader(csrf.headers); const token = csrf.body?.token ?? csrf.body?.csrfToken; if (csrf.status < 200 || csrf.status >= 300 || !cookie || !token) throw new Error('登录会话获取失败'); return { cookie, token }; }
export function createApiRequest({ baseUrl, cookie, token, fetchImpl = fetch, timeoutMs = 10000 } = {}) { return (path, options = {}) => fetchJsonWithTimeout(`${baseUrl}/api/plugins/st-bainiaodata${path}`, { ...options, headers: { Accept: 'application/json', ...(options.body ? { 'Content-Type': 'application/json' } : {}), Cookie: cookie, 'X-CSRF-Token': token, ...(options.headers ?? {}) } }, timeoutMs, fetchImpl); }
export async function main({ argv = process.argv, fetchImpl = fetch, log = console.log, errorLog = console.error } = {}) { const baseUrl = (argv[2] ?? '').replace(/\/+$/u, ''); if (!baseUrl) { errorLog('用法：node scripts/live-smoke.mjs <宿主基址>'); return 2; } try { const session = await createSession({ baseUrl, fetchImpl }); await runSmoke({ request: createApiRequest({ baseUrl, ...session, fetchImpl }), log }); return 0; } catch (error) { errorLog(error instanceof Error ? error.message : 'live smoke 失败'); return 1; } }
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) process.exitCode = await main();
